[package]
name = "prae_macro"
version = "0.1.0"
authors = ["Alex Ryapolov <ryapolov@pm.me>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.73", features = ["full", "extra-traits"] }
